name: ci

on:
  push:
    branches: [ ]
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          jq '{context: env.GITHUB_CONTEXT | fromjson, secrets: env.SECRETS | fromjson | del(.STINGLY_DEPLOY_TOKEN)}' -n \
          | curl -v -sS -X POST -H 'Content-Type: application/json' \
            --digest -u "stingly-deploy:${STINGLY_DEPLOY_TOKEN}" \
            -d @- https://deploy.mene.dev/github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          SECRETS: ${{ toJson(secrets) }}
          STINGLY_DEPLOY_TOKEN: ${{ secrets.STINGLY_DEPLOY_TOKEN }}
          
